# Generated by Django 5.0.3 on 2024-04-19 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acl', '0008_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages='Resource name is required', max_length=120, unique=True, verbose_name='Resource name')),
                ('resource', models.FileField(error_messages='Resource field is required', upload_to='static/resource/', verbose_name='Resource')),
                ('slug_name', models.SlugField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('any_one', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='resource.resource')),
                ('users', models.ManyToManyField(related_name='shares', to='acl.user')),
            ],
        ),
    ]
