# Generated by Django 5.0.3 on 2024-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug_name',
            field=models.SlugField(default='', null=''),
        ),
    ]
