# Generated by Django 5.0.3 on 2024-04-22 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_alter_resource_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresource',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='resource.resource'),
        ),
    ]
