# Generated by Django 5.0.3 on 2024-04-22 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0008_alter_user_picture'),
        ('resource', '0003_alter_shareresource_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='resource.resource'),
        ),
        migrations.AlterField(
            model_name='shareresource',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='shares', to='acl.user'),
        ),
    ]
