# Generated by Django 5.0.3 on 2024-04-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=200)),
                ('remote', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='acl.group'),
        ),
    ]
