# Generated by Django 5.0.3 on 2024-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_alter_permission_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=150),
        ),
    ]
