# Generated by Django 5.0.3 on 2024-04-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0006_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='static/image/default_profile_pic.jpg', upload_to='static/image'),
        ),
    ]
