# Generated by Django 5.0.3 on 2024-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0007_user_in_trash_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='media/images/default_profile_pic.jpg', upload_to='media/images/'),
        ),
    ]
